# Generated by Django 3.2.4 on 2021-07-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Testing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsession',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testsessionofautorizeduser',
            name='testsession_ptr',
        ),
        migrations.RemoveField(
            model_name='testsessionofautorizeduser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testsessionofunautorizeduser',
            name='testsession_ptr',
        ),
        migrations.DeleteModel(
            name='M2MTaskInTestSession',
        ),
        migrations.DeleteModel(
            name='TestSession',
        ),
        migrations.DeleteModel(
            name='TestSessionOfAutorizedUser',
        ),
        migrations.DeleteModel(
            name='TestSessionOfUnautorizedUser',
        ),
    ]
