# Generated by Django 3.2.4 on 2021-07-19 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Task', '0007_auto_20210719_1049'),
        ('Test', '0002_alter_m2mtasklistintest_task_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Testing', '0002_auto_20210719_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='M2MTaskInTestingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, help_text='Чи було надано відповідь на це завдання?', verbose_name='Вирішено')),
                ('order', models.PositiveBigIntegerField(blank=True, default=0, help_text='Чим більше значення, тим пізніше це завдання буде знаходитись у списку завдань сесії', verbose_name='Розташування завдання')),
            ],
            options={
                'verbose_name': 'Список питань в тесті',
                'verbose_name_plural': 'Списки питань в тесті',
                'db_table': 'Testing_task_Testingsession',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField(blank=True, help_text='Початок тестування', verbose_name='Початок')),
                ('end', models.DateTimeField(blank=True, help_text='Дата та час, коли тестування має бути завершено/було завершено', verbose_name='Завершення')),
                ('result', models.DecimalField(blank=True, decimal_places=2, help_text='Результат тестування у відсотках', max_digits=5, null=True, verbose_name='Результат, %')),
                ('tasks', models.ManyToManyField(help_text='Завдання у сесії тестування', through='Testing.M2MTaskInTestingSession', to='Task.Task', verbose_name='Завдання')),
                ('test', models.ForeignKey(help_text='Оберіть тест', on_delete=django.db.models.deletion.CASCADE, to='Test.test', verbose_name='Тест')),
            ],
        ),
        migrations.CreateModel(
            name='TestingSessionOfUnautorizedUser',
            fields=[
                ('testingsession_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Testing.testingsession')),
                ('information', models.CharField(help_text="Прізвище, ім'я, номер групи, тощо", max_length=100, verbose_name='Інформація про користувача')),
            ],
            options={
                'verbose_name': 'Сесія тестування неавторизованого користувача',
                'verbose_name_plural': 'Сесії тестувань неавторизованих користувачів',
            },
            bases=('Testing.testingsession',),
        ),
        migrations.AddField(
            model_name='m2mtaskintestingsession',
            name='session',
            field=models.ForeignKey(help_text='Сесія тестування', on_delete=django.db.models.deletion.CASCADE, related_name='task_set', to='Testing.testingsession', verbose_name='Сесія'),
        ),
        migrations.AddField(
            model_name='m2mtaskintestingsession',
            name='task',
            field=models.ForeignKey(help_text='Завдання для сесії тестування', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_set', to='Task.task', verbose_name='Завдання'),
        ),
        migrations.CreateModel(
            name='TestingSessionOfAutorizedUser',
            fields=[
                ('testingsession_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Testing.testingsession')),
                ('user', models.ForeignKey(help_text='Користувач, що проходив цю сесію тестування', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Коричтувач')),
            ],
            options={
                'verbose_name': 'Сесія тестування авторизованого користувача',
                'verbose_name_plural': 'Сесії тестувань авторизованих користувачів',
            },
            bases=('Testing.testingsession',),
        ),
    ]
