# Generated by Django 3.2.4 on 2021-07-19 15:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0007_auto_20210719_1049'),
        ('Testing', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='m2mtaskintestingsession',
            name='issue_datetime',
            field=models.DateTimeField(blank=True, help_text='Дата та час видачі завдання', null=True, verbose_name='Видано'),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, help_text="Дата та час отримання розв'язку завдання", verbose_name='Дата та час')),
                ('result', models.DecimalField(decimal_places=2, help_text="Результат розв'язку у відсотках", max_digits=5, null=True, verbose_name='Результат, %')),
                ('task_in_testing_session', models.OneToOneField(help_text="Завдання, для якого було отримано цей розв'язок", on_delete=django.db.models.deletion.CASCADE, to='Testing.m2mtaskintestingsession', verbose_name='Завдання з сесії тестування')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceTestSolution',
            fields=[
                ('solution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Testing.solution')),
                ('selected_answers', models.ManyToManyField(help_text='Обрані варіанти відповідей', to='Task.MultipleChoiceTestAnswer', verbose_name='Відповіді')),
            ],
            bases=('Testing.solution',),
        ),
    ]
