# Generated by Django 3.2.6 on 2021-08-17 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0008_auto_20210815_1346'),
        ('Testing', '0004_auto_20210719_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoicetestsolution',
            name='selected_answers',
        ),
        migrations.CreateModel(
            name='M2MSelectedAnswersInMultipleChoiceTestSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.ForeignKey(help_text='Обраний варіант відповіді', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_set', to='Task.multiplechoicetestanswer', verbose_name='Варіант відповіді')),
                ('solution', models.ForeignKey(help_text="Розв'язок завдання", on_delete=django.db.models.deletion.CASCADE, related_name='multiplechoicetestsolution_set', to='Testing.multiplechoicetestsolution', verbose_name="Розв'язок")),
            ],
            options={
                'verbose_name': "Обраний варіант відповіді у розв'язку питання з вибором кількох варіантів",
                'verbose_name_plural': "Обрані варіанти відповіді у розв'язку питання з вибором кількох варіантів",
            },
        ),
    ]
