# Generated by Django 3.2.6 on 2021-08-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0008_auto_20210815_1346'),
        ('Testing', '0005_auto_20210817_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicetestsolution',
            name='selected_answers',
            field=models.ManyToManyField(help_text='Обрані варіанти відповідей', through='Testing.M2MSelectedAnswersInMultipleChoiceTestSolution', to='Task.MultipleChoiceTestAnswer', verbose_name='Відповіді'),
        ),
    ]
