# Generated by Django 3.2.6 on 2021-08-17 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0008_auto_20210815_1346'),
        ('Testing', '0006_multiplechoicetestsolution_selected_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m2mselectedanswersinmultiplechoicetestsolution',
            name='selected_answer',
            field=models.ForeignKey(help_text='Обраний варіант відповіді', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_set', to='Task.multiplechoicetestanswer', verbose_name='Варіант відповіді'),
        ),
        migrations.AlterField(
            model_name='m2mselectedanswersinmultiplechoicetestsolution',
            name='solution',
            field=models.ForeignKey(help_text="Розв'язок завдання", on_delete=django.db.models.deletion.CASCADE, related_name='selected_answer_set', to='Testing.multiplechoicetestsolution', verbose_name="Розв'язок"),
        ),
        migrations.AlterField(
            model_name='m2mtaskintestingsession',
            name='order',
            field=models.PositiveBigIntegerField(blank=True, default=0, help_text='Чим більше значення, тим пізніше це завдання буде знаходитись у списку завдань сесії', verbose_name='Порядок видачі завдання'),
        ),
    ]
