# Generated by Django 3.2.4 on 2021-08-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Testing', '0008_auto_20210824_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testingsessionofunautorizeduser',
            old_name='information',
            new_name='display_name',
        ),
    ]
