# Generated by Django 3.2.4 on 2021-06-23 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Найменування списку завдань', max_length=250, unique=True, verbose_name='Найменування')),
            ],
            options={
                'verbose_name': 'Список завдань',
                'verbose_name_plural': 'Списки завдань',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MultiplyChoiceTest',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Task.task')),
                ('text', models.TextField(blank=True, default='', help_text='Введіть текст завдання для тесту', null=True, verbose_name='Завдання')),
            ],
            options={
                'verbose_name': 'Тест з вибором кількох варіантів відповіді',
                'verbose_name_plural': 'Тести з вибором кількох варіантів відповіді',
            },
            bases=('Task.task',),
        ),
        migrations.AddField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(help_text='Оберіть список завдань', on_delete=django.db.models.deletion.CASCADE, to='Task.tasklist', verbose_name='Список завдань'),
        ),
        migrations.CreateModel(
            name='MultiplyChoiceTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', help_text='Варіант відповіді', null=True, verbose_name='Відповідь')),
                ('weight', models.PositiveSmallIntegerField(default=0, help_text='Чим більше число, тим більший відсоток дасть вибір цього варіанту. 0 - невірний варіант', verbose_name='Вага')),
                ('test', models.ForeignKey(help_text='Оберіть тест', on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to='Task.multiplychoicetest', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Варіант відповіді на тест з вибором кількох варіантів',
                'verbose_name_plural': 'Варіанти відповіді на тести з вибором кількох варіантів',
                'default_related_name': 'answer_set',
            },
        ),
    ]
