# Generated by Django 3.2.4 on 2021-07-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiplychoicetest',
            options={'verbose_name': 'Завдання з вибором кількох варіантів відповіді', 'verbose_name_plural': 'Завдання з вибором кількох варіантів відповіді'},
        ),
    ]
