# Generated by Django 3.2.4 on 2021-07-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_auto_20210719_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplychoicetestanswer',
            old_name='identificator',
            new_name='id',
        ),
    ]
