# Generated by Django 3.2.4 on 2021-07-19 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Testing', '0001_initial'),
        ('Task', '0006_rename_identificator_multiplychoicetestanswer_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultiplyChoiceTest',
            new_name='MultipleChoiceTest',
        ),
        migrations.RenameModel(
            old_name='MultiplyChoiceTestAnswer',
            new_name='MultipleChoiceTestAnswer',
        ),
    ]
