# Generated by Django 3.2.4 on 2021-08-15 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0007_auto_20210719_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Найменування області знань', max_length=250, unique=True, verbose_name='Найменування')),
            ],
            options={
                'verbose_name': 'Область знань',
                'verbose_name_plural': 'Області знань',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['knowledge_field__name', 'name'], 'verbose_name': 'Список завдань', 'verbose_name_plural': 'Списки завдань'},
        ),
        migrations.AddField(
            model_name='tasklist',
            name='knowledge_field',
            field=models.ForeignKey(blank=True, help_text='Оберіть область знань', null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.knowledgefield', verbose_name='Область знань'),
        ),
    ]
