# Generated by Django 3.2.4 on 2021-08-25 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0009_task_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='knowledge_field',
            field=models.ForeignKey(blank=True, help_text='Оберіть область знань', null=True, on_delete=django.db.models.deletion.PROTECT, to='Task.knowledgefield', verbose_name='Область знань'),
        ),
    ]
