# Generated by Django 3.2.4 on 2021-07-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='M2MTaskListInTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_count', models.PositiveSmallIntegerField(help_text='Скільки завдань із вказано списку використовувати у обраному тесті', verbose_name='Кількість завдань')),
                ('task_list', models.ForeignKey(db_column='tasklist_id', help_text='Оберіть список питань', on_delete=django.db.models.deletion.PROTECT, to='Task.tasklist', verbose_name='Список питань')),
            ],
            options={
                'verbose_name': 'Список питань в тесті',
                'verbose_name_plural': 'Списки питань в тесті',
                'db_table': 'Test_tasklist_Test',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Найменування тесту', max_length=150, unique=True, verbose_name='Найменування')),
                ('duration', models.PositiveIntegerField(help_text='Максимально дозволена тривалість тестування у хвилинах', verbose_name='Тривалість, хв')),
                ('is_allowed', models.BooleanField(default=True, help_text='Дозволити проходження тесту', verbose_name='Відкрито')),
                ('is_allow_for_unautorized_users', models.BooleanField(default=False, help_text='Чи дозволено проходження цього тесту для неавторизованих користувачів?', verbose_name='Неавторизовані користувачі')),
                ('task_lists', models.ManyToManyField(help_text='Списки, завдання з яких використовуються у тесті', through='Test.M2MTaskListInTest', to='Task.TaskList', verbose_name='Списки завдань')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тести',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='m2mtasklistintest',
            name='test',
            field=models.ForeignKey(db_column='test_id', help_text='Оберіть тест', on_delete=django.db.models.deletion.CASCADE, to='Test.test', verbose_name='Тест'),
        ),
        migrations.AlterUniqueTogether(
            name='m2mtasklistintest',
            unique_together={('test', 'task_list')},
        ),
    ]
