# Generated by Django 3.2.4 on 2021-07-10 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m2mtasklistintest',
            name='task_count',
            field=models.PositiveSmallIntegerField(help_text='Скільки завдань із вказано списку використовувати у обраному тесті', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кількість завдань'),
        ),
    ]
