# Generated by Django 3.2.4 on 2021-08-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_alter_test_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_allow_help',
            field=models.BooleanField(default=False, help_text='Чи дозволено використовувати підказки?', verbose_name='Підказка'),
        ),
    ]
