# Generated by Django 3.2.4 on 2021-08-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_test_is_allow_skip_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='show_right_solution_after_mistake',
            field=models.BooleanField(default=False, help_text='Показувати вірну відповідь після помилки?', verbose_name='Вірна відповідь'),
        ),
    ]
